### ISSUE TITLE
cannot find module 'rollup-plugin-node-resolve'

### ISSUE THREAD

**Issue by danielduan** [spencermountain/unrequired#3]
```
[!] Error: Cannot find module 'rollup-plugin-node-resolve'
Error: Cannot find module 'rollup-plugin-node-resolve'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
```

Looks like it's actually being used so perhaps it should be inside `dependencies` instead of `devDependencies` in `package.json`

**Comment by spencermountain** [comment]
hey thanks Daniel, released a fix as `0.1.1`
cheers
